### ISSUE TITLE
Do not offer to upload if there is no way to authorize

### ISSUE THREAD

**Issue by jidanni** [nguillaumin/osmtracker-android#109]
In each track's menu there is an option to upload to OSM.

 This option should be greyed out if the authorization option is already also greyed out in the settings menu.

**Comment by nguillaumin** [comment]
The options in the settings is to *reset* the OSM credentials (It's called "Reset OSM authentication", at least in the original EN version). When you haven't uploaded anything to OSM yet, it's grayed out because there are no credentials to reset. I think the option title and description in the app. are self explanatory enough?

Graying out the "upload to OSM" option doesn't make sense I think because that's the only way to upload the data to OSM, regardless if you are already logged in or not. If you never uploaded anything you will be prompted for credentials, otherwise it will just re-use the credentials you entered previously.

So the flow is supposed to be:
* Record a new track ("reset credentials" option is greyed out since no upload ever took place)
* Attempt to upload to OSM
* OSMTracker prompts for OSM credentials
* Track is uploaded
* "Reset credentials" is now available in case something is wrong with the OSM authentication

**Comment by jidanni** [comment]
OK but nobody will ever guess that the way to enter one's credentials is
hidden in a action on the first upload attempt.

They would think it would be irresponsible to upload data without having
logged in first, so would never think to "just go ahead and try it
anyway and see what happens." Also they probably have not read any
manual are just trying their best to use the app.

In fact that is not how most other apps work I recall. And also one
would like to confirm that one's credentials will work before trusting
the app is working enough to go out and start collecting data with it.
Therefore I would also add a Setting where one could enter and test
one's credentials. Yes it could just be the same action that happens
when one tries to upload for the first time, but it should also be
manually accessible from Settings.

**Comment by nguillaumin** [comment]
I tend to disagree. The natural flow in my opinion is to "discover" the app step by step. So first you record a track, then you see that there's an "Upload to OSM" option, you try it, and you get prompted for credentials if necessary.

> just go ahead and try it anyway and see what happens

That's actually exactly what I was aiming for :wink:  and I think most users use apps this way nowadays. They install a bunch of stuff, try to play with them and click a bit randomly to see what can be done.

Contrary to you, I think very few users would have a clue they would need to log-in first via an obscure setting option to be able to upload to OSM. I think It's better to have the authentication happen "in context" while uploading a track, rather than require them to read a manual and realize that they need to pre-authenticate via the settings first.

**Comment by nguillaumin** [comment]
I'm not sure we can convince each other since we both think the other's approach require reading a manual :wink: . That being said, I would recommend googling for some UX patterns like "progressive disclosure" that may clarify what I meant.

**Comment by jidanni** [comment]
I'm saying have both ways available: your original sequence undisturbed,
but just an additional way to access it in Settings, in case the user
wants to see if authorization is working without having to upload random
items first. (Like if I want to test if my telephone is working without
dialing random numbers.)

I think that is how JOSM works, with the two methods.
ID editor too probably: You can log in first, then edit. Or, if not
logged in, it will prompt you to login when you try to edit. Wikipedia too...

Today I'm setting up http://librdf.org/flickcurl/api/flickcurl-auth.html .
That is an example of something one wants to get all set up correctly,
and not wait for a call and then ask the user on the fly...

But OK have it your way.

**Comment by nguillaumin** [comment]
Fair enough, I wouldn't mind if another option were added via a pull request.

**Comment by jjiglesiasg** [comment]
Unable to authenticate to OSM: oauth.signpost.exception.OAuthCommunicationExxception: Communication with the service provider failed responded in error: 500 (Internal Server Error)

This is the message that I get everytime I tryed to upload a trace to OSM

I reinstalled the app 2 times and keep saying the same. Please make this thing more easily. We are mappers no APPs gurus...

**Comment by alantrick** [comment]
@jjiglesiasg https://github.com/labexp/osmtracker-android/issues/137

**Comment by cinclusg** [comment]
I am also getting this message when the app should be prompting me for my osm credentials
Tried reinstalling app. No joy.
oauth.signpost.exception.OAuthCommunicationExxception: Communication with the service provider failed responded in error: 500 (Internal Server Error)
