### ISSUE TITLE
Every jpg is saved in two places!

### ISSUE THREAD

**Issue by jidanni** [nguillaumin/osmtracker-android#111]
Every photograph is saved in two different directories. That makes an average waste of 5 megabytes per photograph!

**Comment by jidanni** [comment]
Okay, maybe it was after I exported it as a GPX.

**Comment by jidanni** [comment]
No. The paths differ by only "data/files /trackNN".

**Comment by nguillaumin** [comment]
It's expected after an export, because they will be present once in the "internal" data folder when the photo is taken, and then once every time it's exported. It's difficult to do otherwise because each exported track needs to be self-contained, so all the resources associated with it (photos, recordings) need to be copied in the track folder.

Until the track is exported, the resources like photos are saved only once in the data folder, I just tested it and it seems to work fine.

Could you try again with a brand new track, taking a single photo and checking the files?

**Comment by nguillaumin** [comment]
Note that there's one folder per track (The `trackNN` you mention), and `NN` should refer to the track number as per the track list in the application. So if you start with a brand new track it will say `#12` for example in the track list, meaning that the corresponding folder should be `data/files/track12`. In this folder you should only have a single copy of the pictures associated with the track.

**Comment by jidanni** [comment]
OK.
By the way, maybe add an option, to save only to pure GPX with no
additional files. No need to change the GPX output (beyond adding an XML
comment "file not saved due to preference"), just don't write the
external files.

By the way, also perhaps add a menu item to delete a GPX. For now we can
create them, but not delete them, without probably using the command to
delete the track source file.
