### ISSUE TITLE
Displaying distance, speed and average speed [patches to follow]

### ISSUE THREAD

**Issue by ars3niy** [nguillaumin/osmtracker-android#56]
Hi Nicolas,

I hope you're doing well, because osmtracker appears to be THE gps tracker on f-droid and so I want to implement that distance, as well as the speed.

Before I start coding, I'd like to ask. How should I implement calculating/storing the total length of the currently recording track?
1) don't store it, calculate it from scratch every second by going through all points in the track;
2) store it in the database right next to name of the track;
3) store it in a new field of TrackLogger or something, update that upon adding new points, pull it from there in Track.build for track that's being recorded, recalculate from scratch for all other tracks; 
4) don't care.

I'd prefer option 3, but maybe you have other ideas?

For now, here's a patch to keep updting "Details" for the track that's being recorded: I want to add length and speed there, and those should be updated (right now it just makes the number of points update, meaning that it works for me).

[osmtracker-update-track-details.txt](https://github.com/nguillaumin/osmtracker-android/files/76809/osmtracker-update-track-details.txt)

**Comment by nguillaumin** [comment]
Thanks for the patch, however would you be able to submit it as a pull request? That would make it easier for me to review and also to comment and discuss on the code if needed, thanks.

Regarding your question I'm not sure. Storing it in the DB doesn't sound ideal as it's duplicating information that can be computed, and there's a risk they may go out of sync for some reason. Also updating the DB schema is a bit involved.

Option 3 sounds the best compromise, but I'm not sure that'll work for the tracks detail screen? It might take a while to re-compute those values when displaying a track since you'll have to query every point in the DB?

I would suggest starting by the simplest possible approach resulting in the simplest code, and see how it performs, and iterate from there?

Closing this one in favour of an hopefully upcoming pull request ;)
