### ISSUE TITLE
Applocation crash when UI language is Hebrew

### ISSUE THREAD

**Issue by zstadler** [nguillaumin/osmtracker-android#70]
If any translation is missing, I'd be happy to provide it.

**Comment by nguillaumin** [comment]
I found the cause, Hebrew has separate layouts and the one for the tracklist item was missing the upload status image. It should be fixed in the next release.

There is already a Hebrew translation but it's incomplete I think, if you want to help we use Transifex for translating the app: https://www.transifex.com/nguillaumin/osmtracker-android/

**Comment by zstadler** [comment]
I've completed the Hebrew (he) translation.
There is no need for a separate "Hebrew (Israel)" (he_IL) translation.

I hope that the translations in the "Tags / buttons strings" section affect only the button strings while the GPX tags remain in English...
