### ISSUE TITLE
™ is not UTF-8

### ISSUE THREAD

**Issue by patmans** [nguillaumin/osmtracker-android#98]
The exported gpx file says it has encoding UTF-8, but it includes the '™' character.

This causes some parsers (i.e. strava.com) to reject the file.

**Comment by nguillaumin** [comment]
Hm, UTF-8 is an encoding of Unicode, and it supports encoding all Unicode characters including ™ AFAIK, so this character is permitted in an UTF-8 encoded XML file (assuming the it's correctly encoded in UTF-8 and not something else like UTF-16).

Could you attach an example GPX file?

**Comment by nguillaumin** [comment]
For reference, ™ UTF-8 encoding is 0xE2 0x84 0xA2: http://www.fileformat.info/info/unicode/char/2122/index.htm

**Comment by patmans** [comment]
See attached gpx file with a  '™' character.

[gpx_example.txt](https://github.com/nguillaumin/osmtracker-android/files/1029580/gpx_example.txt)

**Comment by patmans** [comment]
I'm no export on character sets (especially non-ASCII ones :-) ), but this list of utf8 characters does not include ™, I assume ™ is unicode, but not utf8.

http://www.utf8-chartable.de/unicode-utf8-table.pl?utf8=oct&unicodeinhtml=dec&htmlent=1

**Comment by nguillaumin** [comment]
> I assume ™ is unicode, but not utf8.

That doesn't make sense I think :wink: Unicode has no actual physical representation, to store Unicode data you need to encode it, and UTF-8 is one way to encode it. Unicode and UTF-8 are 2 different concepts, so you can't say that a character is Unicode but not UTF-8. UTF-8 is _one representation_ of Unicode.

Regarding your table, it doesn't show ™ because it only shows the first 255 Unicode characters, and ™ is number 8482 (or 2122 in hexadecimal) (As per my previous link: http://www.fileformat.info/info/unicode/char/2122/index.htm)

Looking at the example GPX file shows that the ™ is properly UTF-8 encoded to 0xE2 0x84 0xA2:

![hex](https://cloud.githubusercontent.com/assets/762512/26472997/bf635c62-415d-11e7-9396-9f3dec40f358.png)

So unless I'm missing something, I think everything is valid and as it's supposed to be. If you encounter an issue with this file it's likely to be a bug in whatever application you're using that doesn't deal properly with UTF-8 encoding. If you want to raise it with the developers of this application feel free to refer to this ticket for details. I'd be happy to be included in the conversation if needed.

**Comment by patmans** [comment]
OK, thanks for the explanation, I'll point them (strava) here and linclude your link - I now see I see the ™ on the web page I was looking at when selecting the U+2100 page.
